### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by picada** [shiftleino/fifteen-puzzle-solver#2]
Project downloaded 27.8.2022 at 13:07

The project seems to be in good shape and the program does what it's supposed to do. Didn't have the patience to wait for the hard mode completion though 😅 

The code is well structured and commented and easy to read. The test coverage is good, and all the test cases seem to be reasonable. All in all good job!

A few minor things that I spotted while going through the code:

- For me it seems like `run_game()` in `main.py` would be more of a UI function and would make sense to just start the program from `main.py` and handle the loop and game initiation from the `console.py` ui class. But could be that there is some reasoning here that I just didn't catch :)
- running `pylint src` reveals some minor code style issues, might want to consider addressing them the ones that are easily fixable
- about getters and setters: using "traditional" getters and setters (such as `get_heuristic()` and `set_heuristic()` isn't maybe the most "pythonic way". Youd could maybe consider using `@property` and `@x.setter` decorators instead? Also if the function doesn't have any additional logic and it's a public property (as all the properties seem to be), you can also just access the property directly
- A small thing, but caught my eye :D In `check_if_solution()` in `solver.py` there's no need for an `if` clause, you could just do `return tile_values == self.correct_solution`

**Comment by shiftleino** [comment]
Thank you for the feedback. You are correct about the run_game()-part, it makes more sense to move it inside the ui-class. And terrific remark about the getters and setters: I actually didn't know that it is not considered as a "pythonic way" of implementing this functionality. I wonder why they teach that in universities (at least where I have learned Python) as the good way of doing. While I personally am not a fan of accessing the attributes of a class directly outside the class, the property-decorator seems to be a clean alternative for doing this. Every day you learn something new, thank you!
